### PR TITLE
added Material Design Icons library

### PR DESCRIPTION
**Pull request by inerba**
added Material Design Icons library [mdi](https://pictogrammers.com/library/mdi/)

### CODE REVIEW

**Comment by driesvints** [comment]
Hi there. These are already added to the list and are maintained by @swapnilsarwe. Thanks

**Comment by inerba** [comment]
Google Material Design Icons and Material Design Icons are distinct projects with different sets of icons, despite having similar names.

**Comment by driesvints** [comment]
Oh I see, sorry about that.

**Comment by driesvints** [comment]
Thanks! Also feel free to send them to the blade ui kit website.

**Comment by swapnilsarwe** [comment]
@inerba 
material-design-icons can be previewed on https://blade-ui-kit.com/blade-icons?set=76

https://github.com/blade-ui-kit/blade-ui-kit.com/pull/120

**Comment by inerba** [comment]
thanks, i updated the readme with a link to Blade UI Kit icon search

**Pull request merged**
