### PR TITLE
New icon sets

### PR DESCRIPTION
**Pull request by swapnilsarwe**
added the following icon sets
- blade-clarity-icons
- blade-line-awesome-icons

### CODE REVIEW

**Comment by driesvints** [comment]
Nice, thanks!

**Comment by driesvints** [comment]
Btw @swapnilsarwe. If you set up something like https://www.buymeacoffee.com I'll try to send a few bucks your way for all your work :)

**Comment by swapnilsarwe** [comment]
@driesvints - never thought of earning a buck or two through this. Hence had never looked up at such options.
Have applied for Github Sponsor Program, but I am in a waitlist. 
In a meanwhile - if you really think its worth, this is my link https://www.buymeacoffee.com/swapnilsarwe

**Comment by driesvints** [comment]
It seems I can't sponsor you 😞

Screen Shot 2021-05-28 at 17 02 44

**Comment by swapnilsarwe** [comment]
No worries 🙂.

**Comment by driesvints** [comment]
@swapnilsarwe someone told me that this should be a setting in your buymeacoffee account. Can you perhaps check if you can enable international payments?

**Comment by swapnilsarwe** [comment]
its pretty new to me. I enabled `Stripe`, `RazorPay` & `Paypal`. Stripe is pending for verification. Lets not rush for it.

Ignore this for now, have a nice weekend. Lets checkout next week.

**Comment by driesvints** [comment]
Cool!

**Pull request merged**
